config/routes.rb
Rails.application.routes.draw do
 
  resources :users
  root to: "users#index"
  get '/search', to:'users#search' 
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :users , dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show ]

  # GET /users or /users.json
  def index
    @users = User.all 
    @address = Address.all   
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @address = Address.new
  end

  
  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
     if @user.save
        @address = Address.create({
          city: params[:user][:address][:city] ,
          country: params[:user][:address][:country] ,
          pin_code: params[:user][:address][:pin_code] ,
          state: params[:user][:address][:state] ,
          street: params[:user][:address][:street] ,
          house_no: params[:user][:address][:house_no] ,
          distt: params[:user][:address][:distt] ,
          user_id: @user.id })
          @address.save!
        format.html { redirect_to root_path, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
        
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def search
    @address = Address.where("city LIKE? OR country LIKE? OR distt LIKE? OR state LIKE?" , "%#{params[:q]}%", "%#{params[:q]}%","%#{params[:q]}%", "%#{params[:q]}%")
    respond_to do |format|
      format.js
      format.html
    end
  end
 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

      # Only allow a list of trusted parameters through.
      def user_params
        params.require(:user).permit(:name, :phone_no, :email, :address => [])
      end
  
     def address_params
      params.require(:user).permit(:address)
     end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: false) do |form| %>
   <div class="modal-body">
        <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :email, class: "form-label" %>
    <%= form.text_field :email, class: "form-control"%>
  </div>

  <div class="field">
    <%= form.label :phone_no , class: "form-label" %>
    <%= form.number_field :phone_no , class: "form-control"%>
  </div>


   <%= form.fields_for @address do |f| %>
    <div class="field">
    <%= f.label :country, class: "form-label" %>
    <%= f.text_field :country , class: "form-control"%>
  </div>
   <div class="field">
    <%= f.label :state, class: "form-label" %>
    <%= f.text_field :state , class: "form-control"%>
  </div>
   <div class="field">
    <%= f.label :distt, class: "form-label" %>
    <%= f.text_field :distt, class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :city , class: "form-label"%>
    <%= f.text_field :city , class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :street , class: "form-label"%>
    <%= f.text_field :street, class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :house_no , class: "form-label"%>
    <%= f.text_field :house_no, class: "form-control" %>
  </div>
   <div class="field">
    <%= f.label :pin_code , class: "form-label"%>
    <%= f.number_field :pin_code , class: "form-control"%>
    </div>
   <%end%>
</div>

 <div class="modal-footer">
   <button type="button" class="btn btn-sm btn-dark" data-bs-dismiss="modal">Close</button>
    <div class="actions">
    <%= form.submit class:"btn btn-sm btn-primary" %>
    </div>
 </div>
  

 
<% end %>

app/views/users/_search.html.erb
<% if @address.count > 0 %>
<h1>Search Results</h1>
<table class="table table-hover">
<thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>District</th>
      <th>State</th>
    </tr>
  </thead>
 <tbody>
   <% @address.each  do |address|%>
      <tr>
        <td><%= address.user.name%></td>
        <td><%= address.city %></td>
        <td><%= address.distt %></td>
        <td><%= address.state %></td>

 </tr>
    <% end %>
  </tbody>
</table>
<%else %>
<h3>No record found </h3>
<%end%>

app/views/users/_show.html.erb
<div class="modal-body">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone no:</strong>
  <%= @user.phone_no %>
</p>
<div class="modal-footer">
   <button type="button" class="btn btn-sm btn-dark" data-bs-dismiss="modal">Close</button>
</div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class ="container">
<nav class="navbar navbar-light bg-dark">

  <div class="container-fluid">
   <%= link_to 'New User', new_user_path ,style:"color:white;text-decoration:none;", data: {bs_toggle:'modal',bs_target: '#newUserModal', remote: true}%>
    <input type="text" id="search" onkeyup = search_user(id) class="form-control" style="width:250px;" placeholder="Search" aria-label="Search" >
    </div>
</nav>

<div id = "address" style="margin-top:20px;">
</div>


<p id="notice"><%= notice %></p>

<% if @users.count > 0 %>
<h1>Users</h1>

<table class="table table-dark table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone no</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.phone_no %></td>
        <td><%= link_to 'Show', user, style:"color:white;text-decoration:none;",
        data: {bs_toggle:'modal',bs_target: '#showUserModal', remote: true}%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%else%>
<h1>Create a User!!</h1>
<%end%>



<script type="text/javascript">
function search_user(){
  var search_result = document.getElementById('search').value
  if(search_result)
  {
    $('#address').show()
    $.ajax({
      url: "<%= search_path%>",
      data:{'q':search_result}
    })
  }
  else{
   $('#address').hide()
  }
}
</script>


<!-- Modal -->
<div class="modal fade" id="newUserModal" tabindex="-1" aria-labelledby="newUserModalLabel" 
aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newUserModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal"
         aria-label="Close"></button>
      </div>
     <div id="newUserForm">
     </div>
    </div>
  </div>
</div>





<!-- Modal -->
<div class="modal fade" id="showUserModal" tabindex="-1" aria-labelledby="showUserModalLabel" 
   aria-hidden="true">
    <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="showUserModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal"
         aria-label="Close"></button>
      </div>
     <div id="showUser">
     </div>
    </div>
  </div>
</div>


</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/new.js.erb
$("#newUserForm").html("<%= escape_javascript render('form', user:@user)%>");

app/views/users/search.js.erb
$('#address').html("<%= j (render 'search')%>");

app/views/users/show.js.erb
$("#showUser").html("<%= escape_javascript render('show')%>");